/**
* COMPANY: holds company id and company code, its the account for which transactions are recorded
**/
create table companies(
    id bigint generated by always as identity,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null,
    constraint companies_users_fkey foreign key(user_id) references public.users(id)
);
